### ISSUE TITLE
FileNotFoundError about IMG_XXX.npy file

### ISSUE THREAD

**Issue by ft-z** [CommissarMa/MCNN-pytorch#6]

**Comment by ft-z** [comment]
I'm sorry that I found it appears on another path.Sorry again!

**Comment by wenzhezhai** [comment]
I have the same problem, please ask what to do，thanks

**Comment by BlouseDong** [comment]
I apologize for the inconvenience. After modifying the paths for the dataset in 'knearestgaussiankernel.py' and 'train.py', I encountered the following error upon running: FileNotFoundError: [Errno 2] No such file or directory: 'D:\zhiwei\MCNN-pytorch\data\ShanghaipartA\traindata\groundtruth\IMG161.npy'.
I'm unsure where the issue lies, and I hope you can provide assistance. Thank you.
